NexxtSao/NexxtSao/Models/MVC/ImgOrthodon.cs
using Resources;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace NexxtSao.Models.MVC
{
    public class ImgOrthodon
    {
        [Key]
        public int ImgOrthodonId { get; set; }

        [Required(ErrorMessageResourceType = typeof(Resource), ErrorMessageResourceName = "Msg_Required")]
        [Range(1, double.MaxValue, ErrorMessageResourceType = typeof(Resource), ErrorMessageResourceName = "Msg_Range")]
        //[Index("Estimate_ClientId_Company_Index", 1, IsUnique = true)]
        [Display(ResourceType = typeof(Resource), Name = "Estimate_Model_Company")]
        public int CompanyId { get; set; }

        [Required(ErrorMessageResourceType = typeof(Resource), ErrorMessageResourceName = "Msg_Required")]
        [Range(1, double.MaxValue, ErrorMessageResourceType = typeof(Resource), ErrorMessageResourceName = "Msg_Range")]
        //[Index("Estimate_ClientId_Company_Index", 2, IsUnique = true)]
        [Display(ResourceType = typeof(Resource), Name = "Estimate_Model_Client")]
        public int ClientId { get; set; }

        [Required(ErrorMessageResourceType = typeof(Resource), ErrorMessageResourceName = "Msg_Required")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Display(ResourceType = typeof(Resource), Name = "Estimate_Model_Date")]
        public DateTime Date { get; set; }

        [DataType(DataType.ImageUrl)]
        [Display(ResourceType = typeof(Resource), Name = "User_Model_Photo")]
        public string Photo { get; set; }

        [MaxLength(512, ErrorMessageResourceType = typeof(Resource), ErrorMessageResourceName = "Msg_MaxLength")]
        [DataType(DataType.MultilineText)]
        [Display(ResourceType = typeof(Resource), Name = "PayDentist_Model_Detalle")]
        public string Detalle { get; set; }


        [NotMapped]
        public HttpPostedFileBase PhotoFile { get; set; }


        public virtual Company Company { get; set; }

        public virtual Client Client { get; set; }
    }
}

NexxtSao/NexxtSao/Controllers/MVC/ImgOrthodonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NexxtSao.Classes;
using NexxtSao.Models;
using NexxtSao.Models.MVC;

namespace NexxtSao.Controllers.MVC
{
    [Authorize(Roles = "User")]

    public class ImgOrthodonsController : Controller
    {
        private NexxtSaoContext db = new NexxtSaoContext();

        // GET: ImgOrthodons
        public ActionResult Index(int? idcliente)
        {
            var user = db.Users.Where(u => u.UserName == User.Identity.Name).FirstOrDefault();
            if (user == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var imgOrthodons = db.ImgOrthodons.Where(c => c.CompanyId == user.CompanyId && c.ClientId == idcliente)
                .Include(i => i.Client);

            return View(imgOrthodons.ToList());
        }

        // GET: ImgOrthodons/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var imgOrthodon = db.ImgOrthodons.Find(id);
            if (imgOrthodon == null)
            {
                return HttpNotFound();
            }
            return View(imgOrthodon);
        }

        // GET: ImgOrthodons/Create
        public ActionResult Create(int idcliente)
        {
            var user = db.Users.Where(u => u.UserName == User.Identity.Name).FirstOrDefault();
            if (user == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var imgorthodon = new ImgOrthodon
            {
                CompanyId = user.CompanyId,
                ClientId = idcliente,
                Date = DateTime.UtcNow
            };

            return View(imgorthodon);
        }

        // POST: ImgOrthodons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ImgOrthodon imgOrthodon)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    db.ImgOrthodons.Add(imgOrthodon);
                    db.SaveChanges();

                    if (imgOrthodon.PhotoFile != null)
                    {
                        var folder = "~/Content/OrthoPhoto";
                        var file = string.Format("{0}.jpg", imgOrthodon.ImgOrthodonId);
                        var response = FilesHelper.UploadPhoto(imgOrthodon.PhotoFile, folder, file);

                        if (response)
                        {
                            var pic = string.Format("{0}/{1}", folder, file);
                            imgOrthodon.Photo = pic;
                            db.Entry(imgOrthodon).State = EntityState.Modified;
                            db.SaveChanges();
                        }
                    }

                    return RedirectToAction("Details", new { id = imgOrthodon.ImgOrthodonId });
                }
                catch (Exception ex)
                {
                    if (ex.InnerException != null &&
                        ex.InnerException.InnerException != null &&
                        ex.InnerException.InnerException.Message.Contains("_Index"))
                    {
                        ModelState.AddModelError(string.Empty, @Resources.Resource.Msg_DoubleData);
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, ex.Message);
                    }
                }
            }

            return View(imgOrthodon);
        }

        // GET: ImgOrthodons/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var imgOrthodon = db.ImgOrthodons.Find(id);
            if (imgOrthodon == null)
            {
                return HttpNotFound();
            }

            return View(imgOrthodon);
        }

        // POST: ImgOrthodons/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ImgOrthodon imgOrthodon)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (imgOrthodon.PhotoFile != null)
                    {
                        var pic = string.Empty;
                        var folder = "~/Content/OrthoPhoto";
                        var file = string.Format("{0}.jpg", imgOrthodon.ImgOrthodonId);
                        var response = FilesHelper.UploadPhoto(imgOrthodon.PhotoFile, folder, file);

                        if (response)
                        {
                            pic = string.Format("{0}/{1}", folder, file);
                            imgOrthodon.Photo = pic;
                        }
                    }

                    db.Entry(imgOrthodon).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Details", new { id = imgOrthodon.ImgOrthodonId });
                }
                catch (Exception ex)
                {
                    if (ex.InnerException != null &&
                        ex.InnerException.InnerException != null &&
                        ex.InnerException.InnerException.Message.Contains("_Index"))
                    {
                        ModelState.AddModelError(string.Empty, @Resources.Resource.Msg_DoubleData);
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, ex.Message);
                    }
                }
            }

            return View(imgOrthodon);
        }

        // GET: ImgOrthodons/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var imgOrthodon = db.ImgOrthodons.Find(id);
            if (imgOrthodon == null)
            {
                return HttpNotFound();
            }
            return View(imgOrthodon);
        }

        // POST: ImgOrthodons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var imgOrthodon = db.ImgOrthodons.Find(id);
            try
            {
                db.ImgOrthodons.Remove(imgOrthodon);
                db.SaveChanges();

                return RedirectToAction("Details", "Orthodontics", new { id = imgOrthodon.ClientId });
            }
            catch (Exception ex)
            {
                if (ex.InnerException != null &&
                    ex.InnerException.InnerException != null &&
                    ex.InnerException.InnerException.Message.Contains("REFERENCE"))
                {
                    ModelState.AddModelError(string.Empty, @Resources.Resource.Msg_Relationship);
                }
                else
                {
                    ModelState.AddModelError(string.Empty, ex.Message);
                }
            }
            return View(imgOrthodon);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NexxtSao/NexxtSao/Views/ImgOrthodons/Create.cshtml
@model NexxtSao.Models.MVC.ImgOrthodon

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "ImgOrthodons", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ImgPhoto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CompanyId)
        @Html.HiddenFor(model => model.ClientId)

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @readonly = "True", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="form-group">
                @Html.LabelFor(model => model.PhotoFile, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <span class="btn btn-default btn-file">
                        @Html.TextBoxFor(modelo => modelo.PhotoFile, new { type = "file" })
                    </span>
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Detalle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Detalle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Detalle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="button" class="btn btn-success btn-sm" onclick="location.href = '@Url.Action("Details", "Orthodontics", new  { id = Model.ClientId})'">
                    <i class="fa fa-backspace"></i>
                    @Resources.Resource.ButtonBack
                </button>

                <button type="submit" class="btn btn-primary btn-sm">
                    <i class="fa fa-save"></i>
                    @Resources.Resource.ButtonSave
                </button>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NexxtSao/NexxtSao/Views/ImgOrthodons/Delete.cshtml
@model NexxtSao.Models.MVC.ImgOrthodon

@{
    ViewBag.Title = "Delete";
}

<p></p>

<h2>@Resources.Resource.ViewDelete</h2>

<h3>@Resources.Resource.MsgDelete</h3>

<p></p>

<div class="row">
    <div class="col-md-12">
        <hr />
        <div class="form-row">
            <div class="col-md-12 mb-1">
                @*<strong> @Html.DisplayNameFor(model => model.Photo)</strong>*@
                <p></p>
                @if (!string.IsNullOrEmpty(Model.Photo))
                {
                    <img src="@Url.Content(Model.Photo)" alt="Image" style="width:900px; height:800px;max-width: 100%; height: auto;" />
                }
            </div>
        </div>

        <p></p>

        <div class="card">
            <h4 class="card-header">@Resources.Resource.Orthodoncia_Panoramica</h4>
            <div class="card-body">
                <div class="form-row">
                    <div class="col-md-4 mb-2">
                        <strong>@Html.DisplayNameFor(model => model.Date)</strong>
                        @Html.DisplayFor(model => model.Date)
                    </div>

                    <div class="col-md-4 mb-2">
                        <strong> @Html.DisplayNameFor(model => model.Client.Cliente)</strong>
                        @Html.DisplayFor(model => model.Client.Cliente)
                    </div>
                </div>

                <div class="form-row">
                    <div class="col-md-12 mb-2">
                        <strong> @Html.DisplayNameFor(model => model.Detalle)</strong>
                        @Html.DisplayFor(model => model.Detalle)
                    </div>
                </div>
                <p></p>
                <hr />
                <div class="form-row">
                    <div class="col-md-6 mb-2">
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <button type="button" class="btn btn-success btn-sm" onclick="location.href = '@Url.Action("Details", "Orthodontics", new { id = Model.ClientId })'">
                                    <i class="fa fa-backspace"></i>
                                    @Resources.Resource.ButtonBack
                                </button>

                                <button type="submit" class="btn btn-danger btn-sm">
                                    <i class="fa fa-trash"></i>
                                    @Resources.Resource.ButtonDelete
                                </button>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

NexxtSao/NexxtSao/Views/ImgOrthodons/Details.cshtml
@model NexxtSao.Models.MVC.ImgOrthodon

@{
    ViewBag.Title = "Details";
}

<p></p>

<div class="row">
    <div class="col-md-12">
        <h4>ImgPhoto</h4>
        <hr />
        <div class="form-row">
            <div class="col-md-12 mb-1">
                @*<strong> @Html.DisplayNameFor(model => model.Photo)</strong>*@
                <p></p>
                @if (!string.IsNullOrEmpty(Model.Photo))
                {
                    <img src="@Url.Content(Model.Photo)" alt="Image" style="width:900px; height:800px;max-width: 100%; height: auto;" />
                }
            </div>
        </div>

        <p></p>

        <div class="card">
            <h4 class="card-header">@Resources.Resource.Orthodoncia_Panoramica</h4>
            <div class="card-body">
                <div class="form-row">
                    <div class="col-md-4 mb-2">
                        <strong>@Html.DisplayNameFor(model => model.Date)</strong>
                        @Html.DisplayFor(model => model.Date)
                    </div>

                    <div class="col-md-4 mb-2">
                        <strong> @Html.DisplayNameFor(model => model.Client.Cliente)</strong>
                        @Html.DisplayFor(model => model.Client.Cliente)
                    </div>
                </div>

                <div class="form-row">
                    <div class="col-md-12 mb-2">
                        <strong> @Html.DisplayNameFor(model => model.Detalle)</strong>
                        @Html.DisplayFor(model => model.Detalle)
                    </div>
                </div>
                <p></p>
                <hr />
                <div class="form-row">
                    <div class="col-md-6 mb-2">
                        <button type="button" class="btn btn-success btn-sm" onclick="location.href = '@Url.Action("Details", "Orthodontics", new { id = Model.ClientId })'">
                            <i class="fa fa-backspace"></i>
                            @Resources.Resource.ButtonBack
                        </button>

                        <button type="submit" class="btn btn-warning btn-sm" onclick="location.href = '@Url.Action("Edit", new { id = Model.ImgOrthodonId })'">
                            <i class="fa fa-pencil-alt"></i>
                            @Resources.Resource.ButtonEdit
                        </button>

                        <a title="Borrar" href="@Url.Action("Delete", new { id = Model.ImgOrthodonId })" class="btn btn-danger btn-sm">
                            <i class="fa fa-trash"></i>
                            @Resources.Resource.ButtonDelete
                        </a>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

NexxtSao/NexxtSao/Views/ImgOrthodons/Edit.cshtml
@model NexxtSao.Models.MVC.ImgOrthodon

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "ImgOrthodons", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ImgPanoramic</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ImgOrthodonId)
        @Html.HiddenFor(model => model.CompanyId)
        @Html.HiddenFor(model => model.ClientId)
        @Html.HiddenFor(model => model.Photo)

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @readonly = "True", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="form-group">
                @Html.LabelFor(model => model.PhotoFile, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <span class="btn btn-default btn-file">
                        @Html.TextBoxFor(modelo => modelo.PhotoFile, new { type = "file" })
                    </span>
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Detalle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Detalle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Detalle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="button" class="btn btn-success btn-sm" onclick="location.href = '@Url.Action("Details", new  { id = Model.ImgOrthodonId})'">
                    <i class="fa fa-backspace"></i>
                    @Resources.Resource.ButtonBack
                </button>

                <button type="submit" class="btn btn-primary btn-sm">
                    <i class="fa fa-save"></i>
                    @Resources.Resource.ButtonSave
                </button>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NexxtSao/NexxtSao/Views/ImgOrthodons/Index.cshtml
@model IEnumerable<NexxtSao.Models.MVC.ImgOrthodon>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

@*<p>
        @Html.ActionLink("Create New", "Create", new { idcliente = Model.ClientId })

    </p>*@
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Client.Cliente)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Photo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Detalle)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Client.Cliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @if (!string.IsNullOrEmpty(item.Photo))
                {
                    <img src="@Url.Content(item.Photo)" alt="Image" style="width:100px;height:100px;max-width: 100%; height: auto;" />
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Detalle)
            </td>
            <td>
                <button title="Editar" class="btn btn-warning btn-sm" onclick="location.href =
                   '@Url.Action("Edit", new { id = item.ImgOrthodonId})'">
                    <i class="fa fa-pencil-alt"></i>
                </button>

                <button title="Detalle" class="btn btn-info btn-sm" onclick="location.href =
                   '@Url.Action("Details", new { id = item.ImgOrthodonId})'">
                    <i class="fa fa-clipboard-list"></i>
                </button>

                <button title="Borrar" class="btn btn-danger btn-sm" onclick="location.href =
                    '@Url.Action("Delete", new { id = item.ImgOrthodonId})'">
                    <i class="fa fa-trash"></i>
                </button>
            </td>
        </tr>
    }

</table>